// Generated by gencpp from file image_msg_pkg/eventResponse.msg
// DO NOT EDIT!


#ifndef IMAGE_MSG_PKG_MESSAGE_EVENTRESPONSE_H
#define IMAGE_MSG_PKG_MESSAGE_EVENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace image_msg_pkg
{
template <class ContainerAllocator>
struct eventResponse_
{
  typedef eventResponse_<ContainerAllocator> Type;

  eventResponse_()
    : b()  {
    }
  eventResponse_(const ContainerAllocator& _alloc)
    : b(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::image_msg_pkg::eventResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::image_msg_pkg::eventResponse_<ContainerAllocator> const> ConstPtr;

}; // struct eventResponse_

typedef ::image_msg_pkg::eventResponse_<std::allocator<void> > eventResponse;

typedef boost::shared_ptr< ::image_msg_pkg::eventResponse > eventResponsePtr;
typedef boost::shared_ptr< ::image_msg_pkg::eventResponse const> eventResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::image_msg_pkg::eventResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::image_msg_pkg::eventResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::image_msg_pkg::eventResponse_<ContainerAllocator1> & lhs, const ::image_msg_pkg::eventResponse_<ContainerAllocator2> & rhs)
{
  return lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::image_msg_pkg::eventResponse_<ContainerAllocator1> & lhs, const ::image_msg_pkg::eventResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace image_msg_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::image_msg_pkg::eventResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_msg_pkg::eventResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::image_msg_pkg::eventResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::image_msg_pkg::eventResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_msg_pkg::eventResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_msg_pkg::eventResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::image_msg_pkg::eventResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ce4159d4691541e9099927d38b0b65f";
  }

  static const char* value(const ::image_msg_pkg::eventResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ce4159d4691541eULL;
  static const uint64_t static_value2 = 0x9099927d38b0b65fULL;
};

template<class ContainerAllocator>
struct DataType< ::image_msg_pkg::eventResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "image_msg_pkg/eventResponse";
  }

  static const char* value(const ::image_msg_pkg::eventResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::image_msg_pkg::eventResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string b\n"
;
  }

  static const char* value(const ::image_msg_pkg::eventResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::image_msg_pkg::eventResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct eventResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::image_msg_pkg::eventResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::image_msg_pkg::eventResponse_<ContainerAllocator>& v)
  {
    s << indent << "b: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMAGE_MSG_PKG_MESSAGE_EVENTRESPONSE_H
