// Generated by gencpp from file image_msg_pkg/event.msg
// DO NOT EDIT!


#ifndef IMAGE_MSG_PKG_MESSAGE_EVENT_H
#define IMAGE_MSG_PKG_MESSAGE_EVENT_H

#include <ros/service_traits.h>


#include <image_msg_pkg/eventRequest.h>
#include <image_msg_pkg/eventResponse.h>


namespace image_msg_pkg
{

struct event
{

typedef eventRequest Request;
typedef eventResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct event
} // namespace image_msg_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::image_msg_pkg::event > {
  static const char* value()
  {
    return "5a6721c091f6b978ce8e7c4a4b79aff1";
  }

  static const char* value(const ::image_msg_pkg::event&) { return value(); }
};

template<>
struct DataType< ::image_msg_pkg::event > {
  static const char* value()
  {
    return "image_msg_pkg/event";
  }

  static const char* value(const ::image_msg_pkg::event&) { return value(); }
};


// service_traits::MD5Sum< ::image_msg_pkg::eventRequest> should match
// service_traits::MD5Sum< ::image_msg_pkg::event >
template<>
struct MD5Sum< ::image_msg_pkg::eventRequest>
{
  static const char* value()
  {
    return MD5Sum< ::image_msg_pkg::event >::value();
  }
  static const char* value(const ::image_msg_pkg::eventRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::image_msg_pkg::eventRequest> should match
// service_traits::DataType< ::image_msg_pkg::event >
template<>
struct DataType< ::image_msg_pkg::eventRequest>
{
  static const char* value()
  {
    return DataType< ::image_msg_pkg::event >::value();
  }
  static const char* value(const ::image_msg_pkg::eventRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::image_msg_pkg::eventResponse> should match
// service_traits::MD5Sum< ::image_msg_pkg::event >
template<>
struct MD5Sum< ::image_msg_pkg::eventResponse>
{
  static const char* value()
  {
    return MD5Sum< ::image_msg_pkg::event >::value();
  }
  static const char* value(const ::image_msg_pkg::eventResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::image_msg_pkg::eventResponse> should match
// service_traits::DataType< ::image_msg_pkg::event >
template<>
struct DataType< ::image_msg_pkg::eventResponse>
{
  static const char* value()
  {
    return DataType< ::image_msg_pkg::event >::value();
  }
  static const char* value(const ::image_msg_pkg::eventResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IMAGE_MSG_PKG_MESSAGE_EVENT_H
