// Generated by gencpp from file image_pkg/AddTwoInts.msg
// DO NOT EDIT!


#ifndef IMAGE_PKG_MESSAGE_ADDTWOINTS_H
#define IMAGE_PKG_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <image_pkg/AddTwoIntsRequest.h>
#include <image_pkg/AddTwoIntsResponse.h>


namespace image_pkg
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace image_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::image_pkg::AddTwoInts > {
  static const char* value()
  {
    return "945e963769938e4ddc3288e80fdfddf4";
  }

  static const char* value(const ::image_pkg::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::image_pkg::AddTwoInts > {
  static const char* value()
  {
    return "image_pkg/AddTwoInts";
  }

  static const char* value(const ::image_pkg::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::image_pkg::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::image_pkg::AddTwoInts >
template<>
struct MD5Sum< ::image_pkg::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::image_pkg::AddTwoInts >::value();
  }
  static const char* value(const ::image_pkg::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::image_pkg::AddTwoIntsRequest> should match
// service_traits::DataType< ::image_pkg::AddTwoInts >
template<>
struct DataType< ::image_pkg::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::image_pkg::AddTwoInts >::value();
  }
  static const char* value(const ::image_pkg::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::image_pkg::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::image_pkg::AddTwoInts >
template<>
struct MD5Sum< ::image_pkg::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::image_pkg::AddTwoInts >::value();
  }
  static const char* value(const ::image_pkg::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::image_pkg::AddTwoIntsResponse> should match
// service_traits::DataType< ::image_pkg::AddTwoInts >
template<>
struct DataType< ::image_pkg::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::image_pkg::AddTwoInts >::value();
  }
  static const char* value(const ::image_pkg::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IMAGE_PKG_MESSAGE_ADDTWOINTS_H
