// Generated by gencpp from file image_pkg/display_edge.msg
// DO NOT EDIT!


#ifndef IMAGE_PKG_MESSAGE_DISPLAY_EDGE_H
#define IMAGE_PKG_MESSAGE_DISPLAY_EDGE_H

#include <ros/service_traits.h>


#include <image_pkg/display_edgeRequest.h>
#include <image_pkg/display_edgeResponse.h>


namespace image_pkg
{

struct display_edge
{

typedef display_edgeRequest Request;
typedef display_edgeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct display_edge
} // namespace image_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::image_pkg::display_edge > {
  static const char* value()
  {
    return "fdd66f87794e274f242af2380bc3fd1f";
  }

  static const char* value(const ::image_pkg::display_edge&) { return value(); }
};

template<>
struct DataType< ::image_pkg::display_edge > {
  static const char* value()
  {
    return "image_pkg/display_edge";
  }

  static const char* value(const ::image_pkg::display_edge&) { return value(); }
};


// service_traits::MD5Sum< ::image_pkg::display_edgeRequest> should match
// service_traits::MD5Sum< ::image_pkg::display_edge >
template<>
struct MD5Sum< ::image_pkg::display_edgeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::image_pkg::display_edge >::value();
  }
  static const char* value(const ::image_pkg::display_edgeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::image_pkg::display_edgeRequest> should match
// service_traits::DataType< ::image_pkg::display_edge >
template<>
struct DataType< ::image_pkg::display_edgeRequest>
{
  static const char* value()
  {
    return DataType< ::image_pkg::display_edge >::value();
  }
  static const char* value(const ::image_pkg::display_edgeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::image_pkg::display_edgeResponse> should match
// service_traits::MD5Sum< ::image_pkg::display_edge >
template<>
struct MD5Sum< ::image_pkg::display_edgeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::image_pkg::display_edge >::value();
  }
  static const char* value(const ::image_pkg::display_edgeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::image_pkg::display_edgeResponse> should match
// service_traits::DataType< ::image_pkg::display_edge >
template<>
struct DataType< ::image_pkg::display_edgeResponse>
{
  static const char* value()
  {
    return DataType< ::image_pkg::display_edge >::value();
  }
  static const char* value(const ::image_pkg::display_edgeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IMAGE_PKG_MESSAGE_DISPLAY_EDGE_H
