// Generated by gencpp from file image_pkg/transport_image.msg
// DO NOT EDIT!


#ifndef IMAGE_PKG_MESSAGE_TRANSPORT_IMAGE_H
#define IMAGE_PKG_MESSAGE_TRANSPORT_IMAGE_H

#include <ros/service_traits.h>


#include <image_pkg/transport_imageRequest.h>
#include <image_pkg/transport_imageResponse.h>


namespace image_pkg
{

struct transport_image
{

typedef transport_imageRequest Request;
typedef transport_imageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct transport_image
} // namespace image_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::image_pkg::transport_image > {
  static const char* value()
  {
    return "fdd66f87794e274f242af2380bc3fd1f";
  }

  static const char* value(const ::image_pkg::transport_image&) { return value(); }
};

template<>
struct DataType< ::image_pkg::transport_image > {
  static const char* value()
  {
    return "image_pkg/transport_image";
  }

  static const char* value(const ::image_pkg::transport_image&) { return value(); }
};


// service_traits::MD5Sum< ::image_pkg::transport_imageRequest> should match
// service_traits::MD5Sum< ::image_pkg::transport_image >
template<>
struct MD5Sum< ::image_pkg::transport_imageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::image_pkg::transport_image >::value();
  }
  static const char* value(const ::image_pkg::transport_imageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::image_pkg::transport_imageRequest> should match
// service_traits::DataType< ::image_pkg::transport_image >
template<>
struct DataType< ::image_pkg::transport_imageRequest>
{
  static const char* value()
  {
    return DataType< ::image_pkg::transport_image >::value();
  }
  static const char* value(const ::image_pkg::transport_imageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::image_pkg::transport_imageResponse> should match
// service_traits::MD5Sum< ::image_pkg::transport_image >
template<>
struct MD5Sum< ::image_pkg::transport_imageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::image_pkg::transport_image >::value();
  }
  static const char* value(const ::image_pkg::transport_imageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::image_pkg::transport_imageResponse> should match
// service_traits::DataType< ::image_pkg::transport_image >
template<>
struct DataType< ::image_pkg::transport_imageResponse>
{
  static const char* value()
  {
    return DataType< ::image_pkg::transport_image >::value();
  }
  static const char* value(const ::image_pkg::transport_imageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IMAGE_PKG_MESSAGE_TRANSPORT_IMAGE_H
