(cl:defpackage color_shape_pair_pkg-srv
  (:use )
  (:export
   "COLOR_EVENT"
   "<COLOR_EVENT-REQUEST>"
   "COLOR_EVENT-REQUEST"
   "<COLOR_EVENT-RESPONSE>"
   "COLOR_EVENT-RESPONSE"
   "EVENT"
   "<EVENT-REQUEST>"
   "EVENT-REQUEST"
   "<EVENT-RESPONSE>"
   "EVENT-RESPONSE"
   "SHAPE_EVENT"
   "<SHAPE_EVENT-REQUEST>"
   "SHAPE_EVENT-REQUEST"
   "<SHAPE_EVENT-RESPONSE>"
   "SHAPE_EVENT-RESPONSE"
  ))

