(cl:defpackage image_pkg-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "DISPLAY_EDGE"
   "<DISPLAY_EDGE-REQUEST>"
   "DISPLAY_EDGE-REQUEST"
   "<DISPLAY_EDGE-RESPONSE>"
   "DISPLAY_EDGE-RESPONSE"
   "TRANSPORT_IMAGE"
   "<TRANSPORT_IMAGE-REQUEST>"
   "TRANSPORT_IMAGE-REQUEST"
   "<TRANSPORT_IMAGE-RESPONSE>"
   "TRANSPORT_IMAGE-RESPONSE"
  ))

