// Generated by gencpp from file color_shape_pair_pkg/color_event.msg
// DO NOT EDIT!


#ifndef COLOR_SHAPE_PAIR_PKG_MESSAGE_COLOR_EVENT_H
#define COLOR_SHAPE_PAIR_PKG_MESSAGE_COLOR_EVENT_H

#include <ros/service_traits.h>


#include <color_shape_pair_pkg/color_eventRequest.h>
#include <color_shape_pair_pkg/color_eventResponse.h>


namespace color_shape_pair_pkg
{

struct color_event
{

typedef color_eventRequest Request;
typedef color_eventResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct color_event
} // namespace color_shape_pair_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::color_shape_pair_pkg::color_event > {
  static const char* value()
  {
    return "6e158a8fb52b65fbc6ac817be43be292";
  }

  static const char* value(const ::color_shape_pair_pkg::color_event&) { return value(); }
};

template<>
struct DataType< ::color_shape_pair_pkg::color_event > {
  static const char* value()
  {
    return "color_shape_pair_pkg/color_event";
  }

  static const char* value(const ::color_shape_pair_pkg::color_event&) { return value(); }
};


// service_traits::MD5Sum< ::color_shape_pair_pkg::color_eventRequest> should match
// service_traits::MD5Sum< ::color_shape_pair_pkg::color_event >
template<>
struct MD5Sum< ::color_shape_pair_pkg::color_eventRequest>
{
  static const char* value()
  {
    return MD5Sum< ::color_shape_pair_pkg::color_event >::value();
  }
  static const char* value(const ::color_shape_pair_pkg::color_eventRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::color_shape_pair_pkg::color_eventRequest> should match
// service_traits::DataType< ::color_shape_pair_pkg::color_event >
template<>
struct DataType< ::color_shape_pair_pkg::color_eventRequest>
{
  static const char* value()
  {
    return DataType< ::color_shape_pair_pkg::color_event >::value();
  }
  static const char* value(const ::color_shape_pair_pkg::color_eventRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::color_shape_pair_pkg::color_eventResponse> should match
// service_traits::MD5Sum< ::color_shape_pair_pkg::color_event >
template<>
struct MD5Sum< ::color_shape_pair_pkg::color_eventResponse>
{
  static const char* value()
  {
    return MD5Sum< ::color_shape_pair_pkg::color_event >::value();
  }
  static const char* value(const ::color_shape_pair_pkg::color_eventResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::color_shape_pair_pkg::color_eventResponse> should match
// service_traits::DataType< ::color_shape_pair_pkg::color_event >
template<>
struct DataType< ::color_shape_pair_pkg::color_eventResponse>
{
  static const char* value()
  {
    return DataType< ::color_shape_pair_pkg::color_event >::value();
  }
  static const char* value(const ::color_shape_pair_pkg::color_eventResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COLOR_SHAPE_PAIR_PKG_MESSAGE_COLOR_EVENT_H
