// Generated by gencpp from file color_shape_pair_pkg/event.msg
// DO NOT EDIT!


#ifndef COLOR_SHAPE_PAIR_PKG_MESSAGE_EVENT_H
#define COLOR_SHAPE_PAIR_PKG_MESSAGE_EVENT_H

#include <ros/service_traits.h>


#include <color_shape_pair_pkg/eventRequest.h>
#include <color_shape_pair_pkg/eventResponse.h>


namespace color_shape_pair_pkg
{

struct event
{

typedef eventRequest Request;
typedef eventResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct event
} // namespace color_shape_pair_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::color_shape_pair_pkg::event > {
  static const char* value()
  {
    return "6e158a8fb52b65fbc6ac817be43be292";
  }

  static const char* value(const ::color_shape_pair_pkg::event&) { return value(); }
};

template<>
struct DataType< ::color_shape_pair_pkg::event > {
  static const char* value()
  {
    return "color_shape_pair_pkg/event";
  }

  static const char* value(const ::color_shape_pair_pkg::event&) { return value(); }
};


// service_traits::MD5Sum< ::color_shape_pair_pkg::eventRequest> should match
// service_traits::MD5Sum< ::color_shape_pair_pkg::event >
template<>
struct MD5Sum< ::color_shape_pair_pkg::eventRequest>
{
  static const char* value()
  {
    return MD5Sum< ::color_shape_pair_pkg::event >::value();
  }
  static const char* value(const ::color_shape_pair_pkg::eventRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::color_shape_pair_pkg::eventRequest> should match
// service_traits::DataType< ::color_shape_pair_pkg::event >
template<>
struct DataType< ::color_shape_pair_pkg::eventRequest>
{
  static const char* value()
  {
    return DataType< ::color_shape_pair_pkg::event >::value();
  }
  static const char* value(const ::color_shape_pair_pkg::eventRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::color_shape_pair_pkg::eventResponse> should match
// service_traits::MD5Sum< ::color_shape_pair_pkg::event >
template<>
struct MD5Sum< ::color_shape_pair_pkg::eventResponse>
{
  static const char* value()
  {
    return MD5Sum< ::color_shape_pair_pkg::event >::value();
  }
  static const char* value(const ::color_shape_pair_pkg::eventResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::color_shape_pair_pkg::eventResponse> should match
// service_traits::DataType< ::color_shape_pair_pkg::event >
template<>
struct DataType< ::color_shape_pair_pkg::eventResponse>
{
  static const char* value()
  {
    return DataType< ::color_shape_pair_pkg::event >::value();
  }
  static const char* value(const ::color_shape_pair_pkg::eventResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COLOR_SHAPE_PAIR_PKG_MESSAGE_EVENT_H
