// Generated by gencpp from file color_shape_pair_pkg/eventResponse.msg
// DO NOT EDIT!


#ifndef COLOR_SHAPE_PAIR_PKG_MESSAGE_EVENTRESPONSE_H
#define COLOR_SHAPE_PAIR_PKG_MESSAGE_EVENTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace color_shape_pair_pkg
{
template <class ContainerAllocator>
struct eventResponse_
{
  typedef eventResponse_<ContainerAllocator> Type;

  eventResponse_()
    : s()  {
    }
  eventResponse_(const ContainerAllocator& _alloc)
    : s(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _s_type;
  _s_type s;





  typedef boost::shared_ptr< ::color_shape_pair_pkg::eventResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::color_shape_pair_pkg::eventResponse_<ContainerAllocator> const> ConstPtr;

}; // struct eventResponse_

typedef ::color_shape_pair_pkg::eventResponse_<std::allocator<void> > eventResponse;

typedef boost::shared_ptr< ::color_shape_pair_pkg::eventResponse > eventResponsePtr;
typedef boost::shared_ptr< ::color_shape_pair_pkg::eventResponse const> eventResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::color_shape_pair_pkg::eventResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::color_shape_pair_pkg::eventResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::color_shape_pair_pkg::eventResponse_<ContainerAllocator1> & lhs, const ::color_shape_pair_pkg::eventResponse_<ContainerAllocator2> & rhs)
{
  return lhs.s == rhs.s;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::color_shape_pair_pkg::eventResponse_<ContainerAllocator1> & lhs, const ::color_shape_pair_pkg::eventResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace color_shape_pair_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::color_shape_pair_pkg::eventResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::color_shape_pair_pkg::eventResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::color_shape_pair_pkg::eventResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::color_shape_pair_pkg::eventResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::color_shape_pair_pkg::eventResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::color_shape_pair_pkg::eventResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::color_shape_pair_pkg::eventResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81af3411577d82a6786258523fc891ce";
  }

  static const char* value(const ::color_shape_pair_pkg::eventResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81af3411577d82a6ULL;
  static const uint64_t static_value2 = 0x786258523fc891ceULL;
};

template<class ContainerAllocator>
struct DataType< ::color_shape_pair_pkg::eventResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "color_shape_pair_pkg/eventResponse";
  }

  static const char* value(const ::color_shape_pair_pkg::eventResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::color_shape_pair_pkg::eventResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string s\n"
;
  }

  static const char* value(const ::color_shape_pair_pkg::eventResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::color_shape_pair_pkg::eventResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.s);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct eventResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::color_shape_pair_pkg::eventResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::color_shape_pair_pkg::eventResponse_<ContainerAllocator>& v)
  {
    s << indent << "s: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.s);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLOR_SHAPE_PAIR_PKG_MESSAGE_EVENTRESPONSE_H
