// Generated by gencpp from file color_shape_pair_pkg/image.msg
// DO NOT EDIT!


#ifndef COLOR_SHAPE_PAIR_PKG_MESSAGE_IMAGE_H
#define COLOR_SHAPE_PAIR_PKG_MESSAGE_IMAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace color_shape_pair_pkg
{
template <class ContainerAllocator>
struct image_
{
  typedef image_<ContainerAllocator> Type;

  image_()
    : a()
    , r(0)
    , g(0)
    , b(0)
    , shape(0)
    , shapex()
    , shapey()  {
    }
  image_(const ContainerAllocator& _alloc)
    : a(_alloc)
    , r(0)
    , g(0)
    , b(0)
    , shape(0)
    , shapex(_alloc)
    , shapey(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _a_type;
  _a_type a;

   typedef int64_t _r_type;
  _r_type r;

   typedef int64_t _g_type;
  _g_type g;

   typedef int64_t _b_type;
  _b_type b;

   typedef int64_t _shape_type;
  _shape_type shape;

   typedef std::vector<int64_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int64_t>> _shapex_type;
  _shapex_type shapex;

   typedef std::vector<int64_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int64_t>> _shapey_type;
  _shapey_type shapey;





  typedef boost::shared_ptr< ::color_shape_pair_pkg::image_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::color_shape_pair_pkg::image_<ContainerAllocator> const> ConstPtr;

}; // struct image_

typedef ::color_shape_pair_pkg::image_<std::allocator<void> > image;

typedef boost::shared_ptr< ::color_shape_pair_pkg::image > imagePtr;
typedef boost::shared_ptr< ::color_shape_pair_pkg::image const> imageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::color_shape_pair_pkg::image_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::color_shape_pair_pkg::image_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::color_shape_pair_pkg::image_<ContainerAllocator1> & lhs, const ::color_shape_pair_pkg::image_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.r == rhs.r &&
    lhs.g == rhs.g &&
    lhs.b == rhs.b &&
    lhs.shape == rhs.shape &&
    lhs.shapex == rhs.shapex &&
    lhs.shapey == rhs.shapey;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::color_shape_pair_pkg::image_<ContainerAllocator1> & lhs, const ::color_shape_pair_pkg::image_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace color_shape_pair_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::color_shape_pair_pkg::image_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::color_shape_pair_pkg::image_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::color_shape_pair_pkg::image_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::color_shape_pair_pkg::image_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::color_shape_pair_pkg::image_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::color_shape_pair_pkg::image_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::color_shape_pair_pkg::image_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e0b06efadd73977cc13f598a4130061";
  }

  static const char* value(const ::color_shape_pair_pkg::image_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e0b06efadd73977ULL;
  static const uint64_t static_value2 = 0xcc13f598a4130061ULL;
};

template<class ContainerAllocator>
struct DataType< ::color_shape_pair_pkg::image_<ContainerAllocator> >
{
  static const char* value()
  {
    return "color_shape_pair_pkg/image";
  }

  static const char* value(const ::color_shape_pair_pkg::image_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::color_shape_pair_pkg::image_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image a\n"
"int64 r\n"
"int64 g\n"
"int64 b\n"
"int64 shape\n"
"int64[] shapex\n"
"int64[] shapey\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::color_shape_pair_pkg::image_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::color_shape_pair_pkg::image_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.r);
      stream.next(m.g);
      stream.next(m.b);
      stream.next(m.shape);
      stream.next(m.shapex);
      stream.next(m.shapey);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct image_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::color_shape_pair_pkg::image_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::color_shape_pair_pkg::image_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.a);
    s << indent << "r: ";
    Printer<int64_t>::stream(s, indent + "  ", v.r);
    s << indent << "g: ";
    Printer<int64_t>::stream(s, indent + "  ", v.g);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
    s << indent << "shape: ";
    Printer<int64_t>::stream(s, indent + "  ", v.shape);
    s << indent << "shapex[]" << std::endl;
    for (size_t i = 0; i < v.shapex.size(); ++i)
    {
      s << indent << "  shapex[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.shapex[i]);
    }
    s << indent << "shapey[]" << std::endl;
    for (size_t i = 0; i < v.shapey.size(); ++i)
    {
      s << indent << "  shapey[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.shapey[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLOR_SHAPE_PAIR_PKG_MESSAGE_IMAGE_H
