// Generated by gencpp from file color_shape_pair_pkg/shape_event.msg
// DO NOT EDIT!


#ifndef COLOR_SHAPE_PAIR_PKG_MESSAGE_SHAPE_EVENT_H
#define COLOR_SHAPE_PAIR_PKG_MESSAGE_SHAPE_EVENT_H

#include <ros/service_traits.h>


#include <color_shape_pair_pkg/shape_eventRequest.h>
#include <color_shape_pair_pkg/shape_eventResponse.h>


namespace color_shape_pair_pkg
{

struct shape_event
{

typedef shape_eventRequest Request;
typedef shape_eventResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct shape_event
} // namespace color_shape_pair_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::color_shape_pair_pkg::shape_event > {
  static const char* value()
  {
    return "ebec1319769de8764c53bcc75605e37a";
  }

  static const char* value(const ::color_shape_pair_pkg::shape_event&) { return value(); }
};

template<>
struct DataType< ::color_shape_pair_pkg::shape_event > {
  static const char* value()
  {
    return "color_shape_pair_pkg/shape_event";
  }

  static const char* value(const ::color_shape_pair_pkg::shape_event&) { return value(); }
};


// service_traits::MD5Sum< ::color_shape_pair_pkg::shape_eventRequest> should match
// service_traits::MD5Sum< ::color_shape_pair_pkg::shape_event >
template<>
struct MD5Sum< ::color_shape_pair_pkg::shape_eventRequest>
{
  static const char* value()
  {
    return MD5Sum< ::color_shape_pair_pkg::shape_event >::value();
  }
  static const char* value(const ::color_shape_pair_pkg::shape_eventRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::color_shape_pair_pkg::shape_eventRequest> should match
// service_traits::DataType< ::color_shape_pair_pkg::shape_event >
template<>
struct DataType< ::color_shape_pair_pkg::shape_eventRequest>
{
  static const char* value()
  {
    return DataType< ::color_shape_pair_pkg::shape_event >::value();
  }
  static const char* value(const ::color_shape_pair_pkg::shape_eventRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::color_shape_pair_pkg::shape_eventResponse> should match
// service_traits::MD5Sum< ::color_shape_pair_pkg::shape_event >
template<>
struct MD5Sum< ::color_shape_pair_pkg::shape_eventResponse>
{
  static const char* value()
  {
    return MD5Sum< ::color_shape_pair_pkg::shape_event >::value();
  }
  static const char* value(const ::color_shape_pair_pkg::shape_eventResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::color_shape_pair_pkg::shape_eventResponse> should match
// service_traits::DataType< ::color_shape_pair_pkg::shape_event >
template<>
struct DataType< ::color_shape_pair_pkg::shape_eventResponse>
{
  static const char* value()
  {
    return DataType< ::color_shape_pair_pkg::shape_event >::value();
  }
  static const char* value(const ::color_shape_pair_pkg::shape_eventResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COLOR_SHAPE_PAIR_PKG_MESSAGE_SHAPE_EVENT_H
