// Generated by gencpp from file color_shape_pair_pkg/shape.msg
// DO NOT EDIT!


#ifndef COLOR_SHAPE_PAIR_PKG_MESSAGE_SHAPE_H
#define COLOR_SHAPE_PAIR_PKG_MESSAGE_SHAPE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace color_shape_pair_pkg
{
template <class ContainerAllocator>
struct shape_
{
  typedef shape_<ContainerAllocator> Type;

  shape_()
    : shape()  {
    }
  shape_(const ContainerAllocator& _alloc)
    : shape(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _shape_type;
  _shape_type shape;





  typedef boost::shared_ptr< ::color_shape_pair_pkg::shape_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::color_shape_pair_pkg::shape_<ContainerAllocator> const> ConstPtr;

}; // struct shape_

typedef ::color_shape_pair_pkg::shape_<std::allocator<void> > shape;

typedef boost::shared_ptr< ::color_shape_pair_pkg::shape > shapePtr;
typedef boost::shared_ptr< ::color_shape_pair_pkg::shape const> shapeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::color_shape_pair_pkg::shape_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::color_shape_pair_pkg::shape_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::color_shape_pair_pkg::shape_<ContainerAllocator1> & lhs, const ::color_shape_pair_pkg::shape_<ContainerAllocator2> & rhs)
{
  return lhs.shape == rhs.shape;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::color_shape_pair_pkg::shape_<ContainerAllocator1> & lhs, const ::color_shape_pair_pkg::shape_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace color_shape_pair_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::color_shape_pair_pkg::shape_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::color_shape_pair_pkg::shape_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::color_shape_pair_pkg::shape_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::color_shape_pair_pkg::shape_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::color_shape_pair_pkg::shape_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::color_shape_pair_pkg::shape_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::color_shape_pair_pkg::shape_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa50c30980f0f012451f487eb6d76d53";
  }

  static const char* value(const ::color_shape_pair_pkg::shape_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa50c30980f0f012ULL;
  static const uint64_t static_value2 = 0x451f487eb6d76d53ULL;
};

template<class ContainerAllocator>
struct DataType< ::color_shape_pair_pkg::shape_<ContainerAllocator> >
{
  static const char* value()
  {
    return "color_shape_pair_pkg/shape";
  }

  static const char* value(const ::color_shape_pair_pkg::shape_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::color_shape_pair_pkg::shape_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string shape\n"
;
  }

  static const char* value(const ::color_shape_pair_pkg::shape_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::color_shape_pair_pkg::shape_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shape);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct shape_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::color_shape_pair_pkg::shape_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::color_shape_pair_pkg::shape_<ContainerAllocator>& v)
  {
    s << indent << "shape: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.shape);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLOR_SHAPE_PAIR_PKG_MESSAGE_SHAPE_H
